"use client";

import { EnvelopeIcon } from "@phosphor-icons/react";

export const PrivacyArea = () => {
  return (
    <>
      <div className="privacy-page">
        <section className="privacy-content container">
          <article>
            <h1>Privacy Policy</h1>
            <p className="last-updated">
              <strong>Last Updated:</strong> August 16, 2025
            </p>

            <h2>1. Introduction and Scope</h2>
            <p>
              This Privacy Policy describes how Bric Advisor ("we," "us," or
              "our") collects, uses, processes, and protects the personal
              information of users ("you," "your," or "users") of our website
              located at{" "}
              <a href="https://www.bricadvisor.com">www.bricadvisor.com</a>{" "}
              (the "Website").
            </p>
            <p>
              We are committed to protecting your privacy and ensuring that your
              Personal Data is processed in compliance with applicable data
              protection laws, including the General Data Protection Regulation
              (GDPR), and the Digital Personal Data Protection Act (DPDPA) 2023.
            </p>

            <h2>2. Types of Personal Data Collected</h2>
            <p>
              We may collect different types of Personal Data from and about
              you, including:
            </p>

            <h3>Identifiers</h3>
            <ul>
              <li>
                Name and contact information (email address, physical address,
                phone number)
              </li>
              <li>Account credentials (username, password)</li>
              <li>IP address and device identifiers</li>
              <li>
                Browser and device information (browser type, version, operating
                system)
              </li>
              <li>Unique identifiers stored in cookies</li>
            </ul>

            <h3>Usage Data</h3>
            <ul>
              <li>
                Information about how you interact with the Website, including
                pages visited, time spent on pages, and click-through data
              </li>
              <li>Search queries and search terms</li>
              <li>Online browsing history</li>
              <li>
                Mobile device information, including unique device identifiers
                and geolocation data (if you have enabled location services)
              </li>
            </ul>

            <h3>Sensitive Personal Information</h3>
            <p>
              We do not collect Sensitive Personal Information (such as
              financial information, precise geolocation, health information,
              biometric data, racial or ethnic origin, religious beliefs, or
              private communications) unless explicitly stated at the point of
              collection and with your specific consent.
            </p>

            <h3>Demographic/Interest Data</h3>
            <ul>
              <li>
                Age, gender, and other demographic information (if voluntarily
                provided)
              </li>
              <li>
                User interests and preferences (inferred from your interactions
                with the Website)
              </li>
              <li>Purchase history (if applicable)</li>
            </ul>

            <h2>3. Methods of Data Collection</h2>
            <p>We collect Personal Data through the following methods:</p>

            <h3>Direct Collection</h3>
            <ul>
              <li>
                When you voluntarily provide information to us (e.g., through
                contact forms, newsletter sign-ups, account registration,
                surveys, or other submissions)
              </li>
              <li>
                When you communicate with us via email, phone, or other channels
              </li>
            </ul>

            <h3>Automatic Collection</h3>
            <ul>
              <li>Through cookies and similar tracking technologies</li>
              <li>
                Through web server logs that automatically record information
                generated by your use of the Website
              </li>
              <li>
                Through analytics providers (e.g., Google Analytics) that
                collect information about your use of the Website
              </li>
              <li>
                Through third-party advertising and marketing technologies
              </li>
            </ul>

            <h2>4. How We Use Your Information</h2>
            <p>
              We collect and process Personal Data for the following purposes:
            </p>

            <h3>To Provide and Maintain Our Services</h3>
            <ul>
              <li>To register and manage your account (if applicable)</li>
              <li>To provide you with the Content and services you request</li>
              <li>To verify your identity and prevent fraud</li>
              <li>To provide customer support and respond to your inquiries</li>
            </ul>

            <h3>To Improve Our Services</h3>
            <ul>
              <li>To analyze and understand how you use our Website</li>
              <li>
                To evaluate and improve our Content, products, and services
              </li>
              <li>To develop new features and functionalities</li>
              <li>To conduct research and analysis</li>
            </ul>

            <h3>For Marketing and Communications</h3>
            <ul>
              <li>
                To send you promotional communications (with your consent)
              </li>
              <li>To personalize your experience on our Website</li>
              <li>To deliver targeted advertising (with your consent)</li>
              <li>To measure the effectiveness of our marketing campaigns</li>
            </ul>

            <h2>5. Legal Basis for Processing</h2>
            <p>
              Under applicable data protection laws, we process Personal Data on
              the following legal bases:
            </p>
            <ul>
              <li>
                <strong>Consent:</strong> When you have given explicit consent
                to the processing of your Personal Data for a specific purpose.
              </li>
              <li>
                <strong>Legitimate Interests:</strong> When necessary for our
                legitimate interests in providing and improving our services,
                provided that these interests are not overridden by your rights
                and freedoms.
              </li>
              <li>
                <strong>Contractual Necessity:</strong> When necessary to
                perform a contract with you or to take steps at your request
                before entering into a contract.
              </li>
              <li>
                <strong>Legal Compliance:</strong> When necessary to comply with
                our legal obligations.
              </li>
            </ul>

            <h2>6. Data Sharing and Disclosure</h2>
            <p>
              We may share your Personal Data with the following categories of
              recipients:
            </p>

            <h3>Service Providers</h3>
            <p>
              We engage third-party companies and individuals to perform
              functions on our behalf, such as:
            </p>
            <ul>
              <li>Website hosting and maintenance</li>
              <li>Data analysis</li>
              <li>Customer service</li>
              <li>Marketing and advertising</li>
              <li>Payment processing (if applicable)</li>
            </ul>
            <p>
              These service providers have access to your Personal Data only to
              perform these tasks on our behalf and are obligated not to
              disclose or use it for any other purpose.
            </p>

            <h3>Business Transfers</h3>
            <p>
              We may share or transfer your Personal Data in connection with, or
              during negotiations of, any merger, sale of company assets,
              financing, or acquisition of all or a portion of our business to
              another company.
            </p>

            <h3>Legal Requirements</h3>
            <p>
              We may disclose your Personal Data if we believe that disclosure
              is necessary:
            </p>
            <ul>
              <li>
                To comply with applicable laws, regulations, or legal processes
              </li>
              <li>
                To respond to lawful requests and public authorities (including
                to meet national security or law enforcement requirements)
              </li>
              <li>
                To protect and defend our rights, property, or safety, or that
                of our users or the public
              </li>
              <li>
                To detect, prevent, or otherwise address fraud, security, or
                technical issues
              </li>
            </ul>

            <div className="highlight-box">
              <p>
                <strong>Note:</strong> In the preceding 12 months, we have not
                sold or shared personal information as defined by the DPDPA. If
                we begin to sell or share personal information in the future, we
                will provide notice and allow you to opt-out.
              </p>
            </div>

            <h2>7. Your Rights and Choices</h2>
            <p>
              Depending on your jurisdiction, you may have the following rights
              regarding your Personal Data:
            </p>
            <ul>
              <li>
                <strong>Right to Access:</strong> Request a copy of the Personal
                Data we hold about you
              </li>
              <li>
                <strong>Right to Rectification/Correction:</strong> Request that
                we correct or update inaccurate or incomplete Personal Data
              </li>
              <li>
                <strong>
                  Right to Deletion/Erasure ("Right to be Forgotten"):
                </strong>{" "}
                Request that we delete your Personal Data, subject to certain
                exceptions
              </li>
              <li>
                <strong>Right to Opt-Out of Sale/Sharing:</strong> If you are a
                California resident, you have the right to opt-out of the sale
                or sharing of your personal information
              </li>
              <li>
                <strong>
                  Right to Limit Use of Sensitive Personal Information:
                </strong>{" "}
                If you are a California resident and we collect sensitive
                personal information, you have the right to limit our use of
                that information
              </li>
              <li>
                <strong>Right to Object/Restrict Processing:</strong> Object to
                or restrict certain types of processing of your Personal Data,
                particularly processing for direct marketing purposes
              </li>
              <li>
                <strong>Right to Data Portability:</strong> Receive a copy of
                your Personal Data in a structured, commonly used, and
                machine-readable format
              </li>
              <li>
                <strong>Right to Withdraw Consent:</strong> Where we rely on
                your consent to process your Personal Data, you have the right
                to withdraw that consent at any time
              </li>
            </ul>

            <p>
              To exercise any of these rights, please contact us using the
              information provided below. We will respond to your request within
              the timeframe required by applicable law.
            </p>

            <h2>8. Data Security</h2>
            <p>
              We implement appropriate technical and organizational measures to
              protect your Personal Data against unauthorized access,
              alteration, disclosure, or destruction. These measures include:
            </p>
            <ul>
              <li>
                Secure Sockets Layer (SSL) encryption for data transmission
              </li>
              <li>Encryption of sensitive data at rest</li>
              <li>Secure password storage and authentication mechanisms</li>
              <li>Regular security assessments and vulnerability testing</li>
              <li>
                Access controls to limit who can access your Personal Data
              </li>
              <li>Employee training on data protection practices</li>
            </ul>
            <p>
              Despite these measures, no internet transmission or electronic
              storage is completely secure. While we strive to protect your
              Personal Data, we cannot guarantee its absolute security.
            </p>

            <h2>9. Data Retention</h2>
            <p>
              We retain your Personal Data only for as long as necessary to
              fulfill the purposes for which it was collected, including for the
              purposes of satisfying any legal, accounting, or reporting
              requirements.
            </p>
            <p>To determine the appropriate retention period, we consider:</p>
            <ul>
              <li>The amount, nature, and sensitivity of the Personal Data</li>
              <li>
                The potential risk of harm from unauthorized use or disclosure
              </li>
              <li>The purposes for which we process your Personal Data</li>
              <li>The applicable legal requirements</li>
            </ul>
            <p>
              When we no longer need your Personal Data, we will securely delete
              or anonymize it.
            </p>

            <h2>10. Policy Updates</h2>
            <p>
              We may update this Privacy Policy from time to time to reflect
              changes in our data practices or applicable laws. When we make
              changes, we will:
            </p>
            <ul>
              <li>
                Revise the "Last Updated" date at the top of this Privacy Policy
              </li>
              <li>
                Notify you by email or through a prominent notice on our Website
                if the changes are material
              </li>
              <li>Obtain your consent if required by applicable law</li>
            </ul>
            <p>
              We encourage you to review this Privacy Policy periodically to
              stay informed about how we collect, use, and protect your Personal
              Data.
            </p>

            <h2>11. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy or concerns
              about how we handle your Personal Data, please contact our
              designated privacy contact:
            </p>
            <div className="contact-info">
              <p>
                {/* <strong>Privacy Contact</strong> */}
                <h5> Bric Advisor</h5>
                <div className="d-flex">
                  <EnvelopeIcon size={30} color="#4c2e88" className="flex-shrink-0 me-2" />
                  <a href="mailto:bricadvisors@gmail.com">
                    bricadvisors@gmail.com
                  </a>
                </div>
              </p>
            </div>
            <p>
              We will investigate and attempt to resolve your complaint promptly
              and in accordance with applicable laws. If you are not satisfied
              with our response, you may have the right to escalate your
              complaint to the relevant data protection authority in your
              jurisdiction.
            </p>

            <div className="highlight-box">
              <p>
                By using Bric Advisor website, you acknowledge that you have
                read, understood, and agree to be bound by this Privacy Policy.
              </p>
            </div>
          </article>
        </section>
      </div>
    </>
  );
};
